# Generated by Django 4.0 on 2022-01-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_usermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
