# Generated by Django 4.0 on 2022-01-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_alter_category_cate_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_mathod',
            field=models.CharField(choices=[('Exclude', 'Exclude'), ('Include', 'Include'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
