# Generated by Django 4.0 on 2022-01-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0007_rename_receiver_type_purchase_purchase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
