# Generated by Django 4.0 on 2022-01-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellmodel',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='order_tax',
            field=models.CharField(choices=[('No tax', 'No tax'), ('VAT @10%', 'VAT @10%'), ('GST @5%', 'GST @5%')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='payment_status',
            field=models.CharField(choices=[('Dew', 'Dew'), ('Payment', 'Payment'), ('Pending', 'Pending')], max_length=50),
        ),
    ]
