# Generated by Django 4.0 on 2022-01-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellApp', '0003_alter_sellmodel_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dew', 'Dew'), ('Payment', 'Payment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='sale_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
