# Generated by Django 4.0 on 2022-01-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellApp', '0005_alter_sellmodel_order_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='order_tax',
            field=models.CharField(choices=[('GST @5%', 'GST @5%'), ('No tax', 'No tax'), ('VAT @10%', 'VAT @10%')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='payment_status',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Pending', 'Pending'), ('Dew', 'Dew')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='sale_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
