# Generated by Django 4.0 on 2022-01-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellApp', '0012_alter_sellmodel_order_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='order_tax',
            field=models.CharField(choices=[('No tax', 'No tax'), ('GST @5%', 'GST @5%'), ('VAT @10%', 'VAT @10%')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dew', 'Dew'), ('Payment', 'Payment')], max_length=50),
        ),
    ]
