# Generated by Django 4.0 on 2022-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellApp', '0016_alter_sellmodel_order_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='payment_status',
            field=models.CharField(choices=[('Dew', 'Dew'), ('Payment', 'Payment'), ('Pending', 'Pending')], max_length=50),
        ),
    ]
