# Generated by Django 4.0 on 2022-01-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellApp', '0027_alter_sellmodel_order_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='order_tax',
            field=models.CharField(choices=[('GST @5%', 'GST @5%'), ('No tax', 'No tax'), ('VAT @10%', 'VAT @10%')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellmodel',
            name='payment_status',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Dew', 'Dew'), ('Pending', 'Pending')], max_length=50),
        ),
    ]
